name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      IMAGEFASTAPI_DB_USER: ${{ secrets.IMAGEFASTAPI_DB_USER }}
      IMAGEFASTAPI_DB_PASSWORD: ${{ secrets.IMAGEFASTAPI_DB_PASSWORD }}
      IMAGEFASTAPI_DB_NAME: myimage_fastapi_test

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.IMAGEFASTAPI_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.IMAGEFASTAPI_DB_PASSWORD }}
          POSTGRES_DB: myimage_fastapi_test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=./" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest app/tests
